Feature/687
Gepardec/mega-frontend pull request #28
Opened 2024-06-10 10:45 UTC by gattrCh

**Prerequisites: Always create two feature branches (frontend + backend) even if your feature only affects one of them**

**DEV:**
> Development
- [ ] Acceptance tests by dev [OpenShift feature environment]
  - [ ] Moved to "Ready for review"

> Review
- [ ] Pull-request reviewed + approved (including Code Coverage) by reviewer [GitHub]
- [ ] Inform dev after review through MEGA-PR (by reviewer) [Chat Space]
- [ ] Version upgrade by dev [GitHub Issue Milestone + maven revision]
- [ ] Merge to main by dev [GitHub]
  - [ ]  Re-add SNAPSHOT to version and push on main [maven revision]
  - [ ]  Make sure all feature branches are deleted [frontend + backend]
  - [ ]  Moved to "Ready for deployment"

> Deployment
- [ ] Integration and Unit tests on main environment passed [Workflow]
- [ ] Deployed to the test environment [GitOps Workflow triggered]
  - [ ] Moved to "Ready for testing"

**PO:**
> Testing
- [ ] Acceptance tests on the test enviroment passed
- [ ] Inspected and approved
  - [ ] Moved to "Ready for release"

2024-06-10 10:54 UTC, Ruhsi requested changes

2024-06-10 10:54 UTC, Ruhsi commented on src/app/domains/project-management/feature-project-management/feature-project-management.component.scss
> +.test {
test??

2024-06-10 10:54 UTC, Ruhsi commented on src/app/domains/project-management/feature-project-management/feature-project-management.component.ts
> +
hm 🤔

2024-06-10 10:54 UTC, Ruhsi commented on src/app/domains/project-management/ui-common/billable-times/billable-times.component.html
> +      {{percentageOfHoursSpentInThisProject + "%"}}
@Ollitod ist hier das % außerhalb schöner/besser? also {{percentageOfHoursSpentInThisProject}} %

2024-06-11 17:21 UTC, Ollitod approved these changes

2024-06-11 17:23 UTC, Ollitod commented on src/app/domains/project-management/ui-common/billable-times/billable-times.component.html
> +      {{percentageOfHoursSpentInThisProject + "%"}}
Ja, außen finde ich es besser.

2024-06-11 17:26 UTC, merged